# Generated by Django 4.0.7 on 2024-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='systemcare_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=20, null=True)),
                ('client_id', models.CharField(max_length=20, null=True)),
                ('Monitor_pH_and_EC', models.CharField(max_length=250, null=True)),
                ('Use_high_quality_nutrient_solution', models.CharField(max_length=250, null=True)),
                ('Clean_nutrient_reservoir_and_misters', models.CharField(max_length=250, null=True)),
                ('Avoid_overwatering', models.CharField(max_length=250, null=True)),
                ('Use_drip_irrigation_system', models.CharField(max_length=250, null=True)),
                ('Flush_nutrient_reservoir_and_misters', models.CharField(max_length=250, null=True)),
                ('Test_nutrient_levels_regularly', models.CharField(max_length=250, null=True)),
                ('Monitor_plants_for_signs_of_nutrient_toxicity', models.CharField(max_length=250, null=True)),
                ('Replace_nutrient_solution', models.CharField(max_length=250, null=True)),
                ('Increase_nutrient_concentration', models.CharField(max_length=250, null=True)),
                ('Add_more_macronutrients', models.CharField(max_length=250, null=True)),
                ('Monitor_plant_growth_and_adjust_nutrient_solution_as_needed', models.CharField(max_length=250, null=True)),
                ('Give_foliar_spray_of_nutrients', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
