# Generated by Django 4.0.7 on 2024-02-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20, null=True)),
                ('empname', models.CharField(max_length=200)),
                ('empemail', models.EmailField(max_length=254, null=True, unique=True)),
                ('empaddress', models.CharField(max_length=200)),
                ('empphone', models.CharField(max_length=200)),
                ('empdepartment', models.CharField(max_length=200)),
                ('emppassword', models.PositiveBigIntegerField(null=True)),
                ('grant', models.BooleanField(default=False, null=True)),
                ('revoke', models.BooleanField(default=False, null=True)),
                ('accept', models.BooleanField(default=False, null=True)),
                ('decline', models.BooleanField(default=False, null=True)),
                ('admit', models.BooleanField(default=False, null=True)),
                ('deny', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
